"""
AdMob Server-Side Verification (SSV) Module
============================================

This module implements cryptographic verification of AdMob rewarded ad callbacks
using Google's Server-Side Verification (SSV) protocol.

When a user completes a rewarded ad, AdMob sends a signed callback URL to the
app's backend. This module verifies that the callback is authentic — i.e., that
it originated from Google and has not been tampered with — before granting any
in-app reward (e.g., coins).

Protocol Overview
-----------------
1. AdMob appends ``signature`` and ``key_id`` query parameters to the callback URL.
2. The data to verify is the raw query string up to (but not including) ``&signature=``.
3. Google signs this data with an ECDSA private key (SHA-256).
4. The verifier fetches the corresponding public key by ``key_id`` from
   ``https://gstatic.com/admob/reward/verifier-keys.json`` and validates the signature.

Classes
-------
- :class:`SecurityError` — Raised when signature verification fails.
- :class:`AdMobSSVVerifier` — Fetches Google's public keys and verifies callback URLs.

Dependencies
------------
- ``requests`` — HTTP client for fetching Google's public key endpoint.
- ``cryptography`` — ECDSA signature verification (``ec``, ``hashes``, ``serialization``).

References
----------
- AdMob SSV documentation: https://developers.google.com/admob/android/ssv
"""
import base64
from urllib.parse import urlparse, parse_qs

import requests
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


class SecurityError(Exception):
    """
    Represents an exception raised for security-related errors.

    This class is a custom exception meant to handle errors that occur
    due to security violations or issues. It extends the base Exception
    class and can be used to raise and manage security-related problems
    in an application.
    """

    pass


class AdMobSSVVerifier:
    """
    A class to verify AdMob server-side verification (SSV) callback URLs.

    This class fetches and manages Google's public keys, and provides functionality
    to cryptographically verify AdMob SSV callback URLs. The primary purpose of
    the verifier is to ensure that the received SSV callback URL is valid and
    originates from Google.

    :ivar KEYS_URL: The URL from which to fetch Google's public keys for signature verification.
    :type KEYS_URL: str
    :ivar keys: A dictionary mapping key IDs to their corresponding public keys.
    :type keys: dict
    """

    KEYS_URL = "https://gstatic.com/admob/reward/verifier-keys.json"

    def __init__(self):
        self.keys = self._fetch_public_keys()

    def _fetch_public_keys(self):
        """
        Fetches and parses public keys from a remote endpoint.

        This method retrieves a collection of public keys in a specific format, processes
        them into a usable form, and returns them as a dictionary where the keys are
        their corresponding unique identifiers. It is designed to handle key data that
        uses base64 encoding and convert it into a usable public key representation.

        :return: A dictionary of parsed public keys where each key is a unique identifier
                 (key ID) and the value is the corresponding public key.
        :rtype: dict
        """
        response = requests.get(self.KEYS_URL)
        response.raise_for_status()
        keys_data = response.json().get("keys", [])

        parsed_keys = {}
        for key in keys_data:
            # Google provides the key in a base64 format (X.509/SubjectPublicKeyInfo)
            key_bytes = base64.b64decode(key["base64"])
            public_key = serialization.load_der_public_key(key_bytes)
            parsed_keys[str(key["keyId"])] = public_key
        return parsed_keys

    def verify(self, callback_url):
        """
        Verifies the authenticity of a callback URL by validating its signature against
        the data contained within the URL query string. This method ensures that the
        callback URL has not been tampered with and was actually generated by the
        expected source.

        :param callback_url: The callback URL to be verified.
        :type callback_url: str

        :return: True if the signature verification is successful, otherwise raises an exception.
        :rtype: bool

        :raises ValueError: If the callback URL is missing required query parameters
            such as "signature" or "key_id", or if the query string is malformed.
        :raises SecurityError: If the signature verification fails, indicating potential
            tampering or invalid data.
        """
        parsed_url = urlparse(callback_url)
        query_string = parsed_url.query

        # 1. Extract signature and key_id
        # We need the raw query string parts because order and format matter
        params = parse_qs(query_string)

        if "signature" not in params or "key_id" not in params:
            raise ValueError("Missing signature or key_id in callback URL")

        signature_str = params["signature"][0]
        key_id = params["key_id"][0]

        # 2. Get the "Data to Verify"
        # This is everything before &signature=...
        # Note: Google's signature and key_id are always the last two params.
        signature_index = query_string.find("&signature=")
        if signature_index == -1:
            raise ValueError("Malformed query string: signature not found")

        data_to_verify = query_string[:signature_index].encode("utf-8")

        # 3. Decode signature (AdMob uses web-safe base64/DER encoding)
        # Python's b64decode handles standard and URL-safe with proper padding
        decoded_signature = base64.urlsafe_b64decode(signature_str + "==")

        # 4. Perform Cryptographic Verification
        if key_id not in self.keys:
            # Refresh keys once if ID is missing (in case of rotation)
            self.keys = self._fetch_public_keys()
            if key_id not in self.keys:
                raise ValueError(f"Key ID {key_id} not found in Google's public keys")

        public_key = self.keys[key_id]

        try:
            public_key.verify(
                decoded_signature, data_to_verify, ec.ECDSA(hashes.SHA256())
            )
            return True
        except Exception as e:
            raise SecurityError("Signature verification failed") from e


# --- Usage Example ---
if __name__ == "__main__":
    # Example URL (replace with actual callback received by your server)
    test_url = "https://myserver.com/reward?ad_network=5450213213286189855&ad_unit=12345678&reward_amount=10&reward_item=coins&timestamp=150777823&transaction_id=12ABC&user_id=1234567&signature=MEUCIQCLJS_s4ia_sN06HqzeW7Wc3nhZi4RlW3qV0oO-6AIYdQIgGJEh-rzKreO-paNDbSCzWGMtmgJHYYW9k2_icM9LFMY&key_id=1234567890"

    verifier = AdMobSSVVerifier()
    try:
        if verifier.verify(test_url):
            print("Verification Successful! Grant reward.")
    except Exception as e:
        print(f"Verification Failed: {e}")
